version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    working_directory: ~/angularCI
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: angularCI-{{ .Branch }}-{{ checksum "package-lock.json"}}
      - run: npm install
      - save_cache:
          key: angularCI-{{ .Branch }}-{{ checksum "package-lock.json"}}
          paths:
            - "nodes_modules"
      - run: npm run test
      - run: npm run build
      - deploy:
          command: |
            ./node_modules/.bin/surge --project ~/angularCI/dist/angularCI --domain angular-circleci.surge.sh
workflows:
    build-and-test:
      jobs:
        - build-and-test
